# Generated by Django 4.1.1 on 2022-09-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0004_pat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pat",
        ),
    ]
